- name: Init os var
  include_vars: "vars/{{ ansible_system | lower }}.yml"

- name: Check server exist
  stat:
    path: "{{ wireguarddir }}/{{ servername }}.conf"
  register: serverconf

- name: Generated private key
  command: wg genkey
  register: privkey
  when: not serverconf.stat.exists

- name: Init server conf
  template:
    src: templates/server.conf
    dest: "{{ wireguarddir }}/{{ servername }}.conf"
  become: true
  when: not serverconf.stat.exists
