- name: Set now ip init
  set_fact:
    nowip: ""

- name: ipv6 first random
  shell: xxd -l "{{ (128 - (serveriptmp | ansible.utils.ipaddr('prefix'))) / 8 }}" -ps /dev/urandom
  register: getcount6init

- name: Set now ip
  set_fact:
    nowip: "{% if item != '' and (serveriptmp | ansible.utils.ipaddr('subnet')) == ((item+'/'+(serveriptmp | ansible.utils.ipaddr('prefix') | string)) | ansible.utils.ipaddr('subnet')) %}{{ item+'/'+(serveriptmp | ansible.utils.ipaddr('prefix') | string) }}{% elif item == '' and (serveriptmp | ansible.utils.ipv4) %}{{ serveriptmp | ansible.utils.ipaddr('subnet') | ansible.utils.ipaddr('1') }}{% elif item == '' and (serveriptmp | ansible.utils.ipv6) %}{{ serveriptmp | ansible.utils.ipaddr('subnet') | ansible.utils.ipaddr(getcount6init.stdout | int(base=16) | string) }}{% else %}{{''}}{% endif %}"
  when: nowip == ""
  with_items: 
    - "{{ addresseslist + [''] }}"

- name: Init Choose IP address
  shell: if [ -e /tmp/.temp.conf ]; then rm /tmp/.temp.conf; fi

- name: Choose IP address (ipv4)
  shell: if [ -f /tmp/.temp.conf ]; then tmp=$(($(cat /tmp/.temp.conf) + 1)) && echo $tmp | tee /tmp/.temp.conf; else echo 0 | tee /tmp/.temp.conf; fi
  register: getcount4
  until: ((nowip | ansible.utils.next_nth_usable(getcount4.stdout | int)) == "") or ((serverconfigcontent.content | b64decode | regex_search('(AllowedIPs|Address)\\s*=\\s*.*('+((nowip | ansible.utils.next_nth_usable(getcount4.stdout | int)).replace('.', '\\.'))+')/.*', '\\2')) is none)
  retries: "{{ serveriptmp | ansible.utils.ipaddr('size') }}"
  delay: 0
  when: (serveriptmp | ansible.utils.ipv4) and nowip and ((serverconfigcontent.content | b64decode | regex_search('(AllowedIPs|Address)\\s*=\\s*.*('+(nowip.replace('.', '\\.') | regex_replace('/.*', ''))+')/.*', '\\2')) is not none)

- name: Choose IP address (ipv6)
  #shell: xxd -l 8 -ps /dev/urandom | sed 's/.\{4\}/&:/g' | sed 's/:$//g'
  shell: xxd -l "{{ (128 - (serveriptmp | ansible.utils.ipaddr('prefix'))) / 8 }}" -ps /dev/urandom
  register: getcount6
  until: ((nowip | ansible.utils.ipaddr(getcount6.stdout | int(base=16) | string) | regex_replace('/.*', '')) == "") or ((serverconfigcontent.content | b64decode | regex_search('(AllowedIPs|Address)\\s*=\\s*.*('+((nowip | ansible.utils.ipaddr(getcount6.stdout | int(base=16) | string) | regex_replace('/.*', '')).replace('.', '\\.'))+')/.*', '\\2')) is none)
  retries: 9999
  delay: 0
  when: (serveriptmp | ansible.utils.ipv6) and nowip and ((serverconfigcontent.content | b64decode | regex_search('(AllowedIPs|Address)\\s*=\\s*.*('+(nowip.replace('.', '\\.') | regex_replace('/.*', ''))+')/.*', '\\2')) is not none)

- name: Set new nowip (ipv4)
  set_fact:
    nowip: "{{ nowip | ansible.utils.next_nth_usable(getcount4.stdout | int) }}/{{ nowip | ansible.utils.ipaddr('prefix') }}"
  when: (serveriptmp | ansible.utils.ipv4) and "stdout" in getcount4

- name: Set new nowip (ipv6)
  set_fact:
    nowip: "{{ nowip | ansible.utils.ipaddr(getcount6.stdout | int(base=16) | string) }}"
  when: (serveriptmp | ansible.utils.ipv6) and "stdout" in getcount6

- name: Add client ips
  set_fact:
    clientips: "{{ clientips + [nowip] }}"
  when: (serveriptmp | ansible.utils.ipaddr('subnet')) == (nowip | ansible.utils.ipaddr('subnet'))

- name: Add serverrouteforclient ips (ipv4)
  set_fact:
    serverrouteforclient: "{{ serverrouteforclient + [nowip | regex_replace('/.*', '/32')] }}"
  when: (serveriptmp | ansible.utils.ipaddr('subnet')) == (nowip | ansible.utils.ipaddr('subnet')) and (nowip | ansible.utils.ipv4)

- name: Add serverrouteforclient ips (ipv6)
  set_fact:
    serverrouteforclient: "{{ serverrouteforclient + [nowip | regex_replace('/.*', '/128')] }}"
  when: (serveriptmp | ansible.utils.ipaddr('subnet')) == (nowip | ansible.utils.ipaddr('subnet')) and (nowip | ansible.utils.ipv6)
